"""
Item type code → human-readable base name.
Codes are 4 chars padded with spaces (e.g. 'cm1 ', 'rin ') when used as keys.
Strip with .strip() for lookup. Values come from MOD_ITEM_NAMES in the old _d2i_tables.py.
"""
from __future__ import annotations

ITEM_TYPES: dict[str, str] = {
    # ── Runes ──────────────────────────────────────────────────────────────────
    "r01": "El Rune",    "r02": "Eld Rune",   "r03": "Tir Rune",   "r04": "Nef Rune",
    "r05": "Eth Rune",   "r06": "Ith Rune",   "r07": "Tal Rune",   "r08": "Ral Rune",
    "r09": "Ort Rune",   "r10": "Thul Rune",  "r11": "Amn Rune",   "r12": "Sol Rune",
    "r13": "Shael Rune", "r14": "Dol Rune",   "r15": "Hel Rune",   "r16": "Io Rune",
    "r17": "Lum Rune",   "r18": "Ko Rune",    "r19": "Fal Rune",   "r20": "Lem Rune",
    "r21": "Pul Rune",   "r22": "Um Rune",    "r23": "Mal Rune",   "r24": "Ist Rune",
    "r25": "Gul Rune",   "r26": "Vex Rune",   "r27": "Ohm Rune",   "r28": "Lo Rune",
    "r29": "Sur Rune",   "r30": "Ber Rune",   "r31": "Jah Rune",   "r32": "Cham Rune",
    "r33": "Zod Rune",
    # ── Charms ─────────────────────────────────────────────────────────────────
    "cm1": "Small Charm", "cm2": "Large Charm", "cm3": "Grand Charm",
    # ── Jewelry & miscellaneous ─────────────────────────────────────────────────
    "rin": "Ring", "amu": "Amulet", "jew": "Jewel",
    # ── Gems: Chipped / Flawed / Normal / Flawless / Perfect ───────────────────
    "gcv": "Chipped Amethyst",  "gfv": "Flawed Amethyst",  "gsv": "Amethyst",
    "gzv": "Flawless Amethyst", "gpv": "Perfect Amethyst",
    "gcy": "Chipped Topaz",     "gfy": "Flawed Topaz",     "gsy": "Topaz",
    "gly": "Flawless Topaz",    "gpy": "Perfect Topaz",
    "gcb": "Chipped Sapphire",  "gfb": "Flawed Sapphire",  "gsb": "Sapphire",
    "glb": "Flawless Sapphire", "gpb": "Perfect Sapphire",
    "gcg": "Chipped Emerald",   "gfg": "Flawed Emerald",   "gsg": "Emerald",
    "gig": "Flawless Emerald",  "gpg": "Perfect Emerald",
    "gcr": "Chipped Ruby",      "gfr": "Flawed Ruby",      "gsr": "Ruby",
    "glr": "Flawless Ruby",     "gpr": "Perfect Ruby",
    "gcw": "Chipped Diamond",   "gfw": "Flawed Diamond",   "gsw": "Diamond",
    "glw": "Flawless Diamond",  "gpw": "Perfect Diamond",
    "skc": "Chipped Skull",     "skf": "Flawed Skull",     "sku": "Skull",
    "skl": "Flawless Skull",    "skz": "Perfect Skull",
    # ── Quest / special items ───────────────────────────────────────────────────
    "key": "Key", "box": "Horadric Cube", "bks": "Scroll of Inifuss",
    "pk1": "Key of Terror", "pk2": "Key of Hate", "pk3": "Key of Destruction",
    "bey": "Baal's Eye", "mbr": "Mephisto's Brain", "dhn": "Diablo's Horn",
    "ua1": "Ancient Key (Act 1)", "ua2": "Ancient Key (Act 2)", "ua3": "Ancient Key (Act 3)",
    "ua4": "Ancient Key (Act 4)", "ua5": "Ancient Key (Act 5)",
    "tr1": "Token of Absolution",
    # ── Helmets: Normal / Exceptional / Elite ──────────────────────────────────
    "cap": "Cap",        "skp": "Skull Cap",  "hlm": "Helm",
    "fhl": "Full Helm",  "ghm": "Great Helm", "crn": "Crown",  "msk": "Mask",
    "xap": "War Hat",    "xkp": "Sallet",     "xlm": "Casque",
    "xhl": "Basinet",    "xhm": "Giant Conch","xrn": "Winged Helm", "xsk": "Death Mask",
    "uap": "Shako",      "ukp": "Hydraskull", "ulm": "Armet",
    "uhl": "Giant Skull","uhm": "Spired Helm","urn": "Corona", "usk": "Demonhead",
    # ── Body Armor: Normal / Exceptional / Elite ────────────────────────────────
    "qui": "Quilted Armor",   "lea": "Leather Armor",    "hla": "Hard Leather Armor",
    "stu": "Studded Leather", "rng": "Ring Mail",         "scl": "Scale Mail",
    "chn": "Chain Mail",      "brs": "Breast Plate",      "spl": "Splint Mail",
    "plt": "Plate Mail",      "fld": "Field Plate",       "gth": "Gothic Plate",
    "ful": "Full Plate Mail", "arm": "Ancient Armor",     "ltp": "Light Plate",
    "xui": "Ghost Armor",     "xea": "Serpentskin Armor", "xla": "Demonhide Armor",
    "xtu": "Trellised Armor", "xng": "Linked Mail",       "xcl": "Tiger Mail",
    "xhn": "Mesh Armor",      "xrs": "Cuirass",           "xpl": "Russet Armor",
    "xlt": "Mage Plate",      "xld": "Boneweave",         "xth": "Balrog Skin",
    "xul": "Chaos Armor",     "xar": "Ornate Armor",
    "uui": "Dusk Shroud",     "uea": "Wyrmhide",          "ula": "Scarab Husk",
    "utu": "Wire Fleece",     "ung": "Diamond Mail",      "ucl": "Loricated Mail",
    "uhn": "Boneweave",       "urs": "Great Hauberk",     "upl": "Hellforge Plate",
    "ult": "Archon Plate",    "uld": "Kraken Shell",      "uth": "Lacquered Plate",
    "uul": "Shadow Plate",    "uar": "Sacred Armor",
    # ── Shields: Normal / Exceptional / Elite ──────────────────────────────────
    "buc": "Buckler",       "sml": "Small Shield",  "lrg": "Large Shield",
    "kit": "Kite Shield",   "tow": "Tower Shield",  "gts": "Gothic Shield",
    "xuc": "Defender",      "xml": "Round Shield",  "xlg": "Scutum",
    "xks": "Dragon Shield", "xow": "Pavise",        "xts": "Ancient Shield",
    "uuc": "Heater",        "uml": "Luna",          "ulg": "Hyperion",
    "uks": "Monarch",       "uow": "Aegis",         "uts": "Ward",
    # ── Gloves: Normal ─────────────────────────────────────────────────────────
    "lgl": "Leather Gloves", "vgl": "Heavy Gloves",     "mgl": "Chain Gloves",
    "tgl": "Light Gauntlets","hgl": "Gauntlets",
    # ── Boots: Normal ──────────────────────────────────────────────────────────
    "lbt": "Leather Boots",  "vbt": "Heavy Boots",      "mbt": "Chain Boots",
    "tbt": "Light Plate Boots","hbt": "Battle Boots",
    # ── Belts: Normal ──────────────────────────────────────────────────────────
    "blt": "Sash",  "vbl": "Light Belt", "mbl": "Belt", "tbl": "Heavy Belt", "hbl": "Plated Belt",
    # ── Weapons: Swords ─────────────────────────────────────────────
    "ssd": "Short Sword",
    "lsd": "Long Sword",
    "bsd": "Broad Sword",
    "scm": "Scimitar",
    "sbr": "Saber",
    "flc": "Falchion",
    "crs": "Crystal Sword",
    "bsw": "Bastard Sword",
    "clm": "Claymore",
    "gis": "Giant Sword",
    "gsd": "Great Sword",
    "2hs": "Two-Handed Sword",
    "9ss": "Gladius",
    "9bs": "Battle Sword",
    "9ls": "Rune Sword",
    "9cs": "Hand Scythe",
    "9b9": "Gothic Sword",
    "9ws": "Divine Scepter",
    "9wd": "Ancient Sword",
    "9sm": "Cutlass",
    "9sb": "Shamshir",
    "9cm": "Dacian Falx",
    "9gs": "Tusk Sword",
    "9dg": "Poignard",
    "9di": "Rondel",
    "9bl": "Stilleto",
    "9fc": "Tulwar",
    "9fb": "Zweihander",
    "7ss": "Falcata",
    "7bs": "Conquest Sword",
    "7ls": "Cryptic Sword",
    "7cs": "Battle Cestus",
    "7wd": "Mythical Sword",
    "7fb": "Colossal Sword",
    "7fc": "Hydra Edge",
    "7sm": "Ataghan",
    "7sb": "Elegant Blade",
    "7cm": "Highland Blade",
    "7gs": "Balrog Blade",
    "7dg": "Bone Knife",
    "7di": "Mithral Point",
    "7bl": "Legend Spike",
    "7b7": "Champion Sword",
    "72h": "Legend Sword",
    "7gd": "Colossus Blade",
    "7cr": "Phase Blade",
    "7ws": "Caduceus",

    # ── Weapons: Axes ───────────────────────────────────────────────
    "hax": "Hand Axe",
    "axe": "Axe",
    "lax": "Large Axe",
    "2ax": "Double Axe",
    "gax": "Great Axe",
    "gix": "Giant Axe",
    "btx": "Battle Axe",
    "bax": "Broad Axe",
    "wax": "War Axe",
    "mau": "Maul",
    "gma": "Great Maul",
    "9ax": "Cleaver",
    "9ha": "Hatchet",
    "9la": "Military Axe",
    "9ba": "Bearded Axe",
    "9ga": "Gothic Axe",
    "9gi": "Ancient Axe",
    "9wa": "Naga",
    "9bt": "Tabar",
    "7ax": "Small Crescent",
    "7ha": "Tomahawk",
    "7la": "Feral Axe",
    "7ba": "Silver-edged Axe",
    "7ga": "Champion Axe",
    "7gi": "Glorious Axe",
    "7wa": "Berserker Axe",
    "7bt": "Decapitator",
    "72a": "Ettin Axe",

    # ── Weapons: Maces ──────────────────────────────────────────────
    "clb": "Club",
    "spc": "Spiked Club",
    "mst": "Morning Star",
    "fla": "Flail",
    "mac": "Mace",
    "whm": "War Hammer",
    "9cl": "Cudgel",
    "9sp": "Barbed Club",
    "9ma": "Flanged Mace",
    "9fl": "Knout",
    "9wh": "Battle Hammer",
    "9gm": "Martel de Fer",
    "9mt": "Jagged Star",
    "9m9": "War Club",
    "7cl": "Truncheon",
    "7sp": "Tyrant Club",
    "7ma": "Reinforced Mace",
    "7fl": "Scourge",
    "7wh": "Legendary Mallet",
    "7gm": "Thunder Maul",
    "7mt": "Devil Star",
    "7m7": "Ogre Maul",

    # ── Weapons: Polearms ───────────────────────────────────────────
    "bar": "Bardiche",
    "pax": "Poleaxe",
    "hal": "Halberd",
    "scy": "Scythe",
    "wsc": "War Scythe",
    "vou": "Voulge",
    "glv": "Glaive",
    "bld": "Blade",
    "9b7": "Lochaber Axe",
    "9s8": "Battle Scythe",
    "9wc": "Grim Scythe",
    "9h9": "Bec-de-Corbin",
    "9pa": "Partizan",
    "9gl": "Spiculum",
    "7s8": "Thresher",
    "7wc": "Giant Thresher",
    "7h7": "Great Poleaxe",
    "7pa": "Cryptic Axe",
    "7gl": "Ghost Glaive",
    "7o7": "Ogre Axe",
    "7vo": "Colossus Voulge",

    # ── Weapons: Spears ─────────────────────────────────────────────
    "spr": "Spear",
    "spt": "Spetum",
    "tri": "Trident",
    "brn": "Brandistock",
    "pik": "Pike",
    "9sr": "War Spear",
    "9tr": "Fuscina",
    "9p9": "Lance",
    "9st": "Yari",
    "7sr": "Hyperion Spear",
    "7tr": "Stygian Pike",
    "7p7": "War Pike",
    "7st": "Ghost Spear",

    # ── Weapons: Staves ─────────────────────────────────────────────
    "sst": "Short Staff",
    "lst": "Long Staff",
    "cst": "Gnarled Staff",
    "bst": "Battle Staff",
    "wst": "War Staff",
    "gsc": "Grand Scepter",
    "8ss": "Jo Staff",
    "8ls": "Quarterstaff",
    "8cs": "Cedar Staff",
    "8bs": "Gothic Staff",
    "8ws": "Rune Staff",
    "6ss": "Walking Stick",
    "6ls": "Stalagmite",
    "6cs": "Elder Staff",
    "6bs": "Shillelagh",
    "6ws": "Archon Staff",

    # ── Weapons: Wands ──────────────────────────────────────────────
    "wnd": "Wand",
    "ywn": "Yew Wand",
    "bwn": "Bone Wand",
    "gwn": "Grim Wand",
    "9wn": "Burnt Wand",
    "9bw": "Tomb Wand",
    "9yw": "Petrified Wand",
    "7wn": "Polished Wand",
    "7bw": "Lich Wand",
    "7yw": "Ghost Wand",

    # ── Weapons: Bows/Xbows ─────────────────────────────────────────
    "sbw": "Short Bow",
    "hbw": "Hunter's Bow",
    "lbw": "Long Bow",
    "cbw": "Composite Bow",
    "sbb": "Short Battle Bow",
    "lbb": "Long Battle Bow",
    "swb": "Short War Bow",
    "lwb": "Long War Bow",
    "lxb": "Light Crossbow",
    "mxb": "Crossbow",
    "hxb": "Heavy Crossbow",
    "rxb": "Repeating Crossbow",
    "8sb": "Edge Bow",
    "8lb": "Cedar Bow",
    "8cb": "Double Bow",
    "8hb": "Razor Bow",
    "8sw": "Rune Bow",
    "8lw": "Gothic Bow",
    "8s8": "Short Siege Bow",
    "8l8": "Long Siege Bow",
    "8lx": "Arbalest",
    "8mx": "Siege Crossbow",
    "8hx": "Ballista",
    "8rx": "Chu-Ko-Nu",
    "6sb": "Spider Bow",
    "6lb": "Shadow Bow",
    "6cb": "Great Bow",
    "6hb": "Blade Bow",
    "6sw": "Ward Bow",
    "6lw": "Hydra Bow",
    "6s7": "Diamond Bow",
    "6l7": "Crusader Bow",
    "6lx": "Pellet Bow",
    "6mx": "Gorgon Crossbow",
    "6hx": "Colossus Crossbow",
    "6rx": "Demon Crossbow",

    # ── Weapons: Throwing ───────────────────────────────────────────
    "tax": "Throwing Axe",
    "tkf": "Throwing Knife",
    "bal": "Balanced Axe",
    "bkf": "Balanced Knife",
    "9ta": "Francisca",
    "9tk": "Battle Dart",
    "9bk": "War Dart",
    "9b8": "Hurlbat",
    "7ta": "Flying Axe",
    "7tk": "Flying Knife",
    "7bk": "Winged Knife",
    "7b8": "Winged Axe",

    # ── Weapons: Katars ─────────────────────────────────────────────
    "ktr": "Katar",
    "wrb": "Wrist Blade",
    "clw": "Claws",
    "btl": "Blade Talons",
    "ces": "Cestus",
    "skr": "Scissors Katar",
    "axf": "Hatchet Hands",
    "9ar": "Quhab",
    "9qr": "Scissors Quhab",
    "9lw": "Greater Claws",
    "9xf": "Fascia",
    "7ar": "Suwayyah",
    "7qr": "Scissors Suwayyah",
    "7lw": "Feral Claws",
    "7xf": "War Fist",
    "7wb": "Wrist Sword",
    "7tw": "Runic Talons",

    # ── Weapons: Other ──────────────────────────────────────────────
    "dgr": "Dagger",
    "dir": "Dirk",
    "kri": "Kriss",
    "jav": "Javelin",
    "pil": "Pilum",
    "ssp": "Short Spear",
    "tsp": "Throwing Spear",
    "scp": "Scepter",
    "wsp": "War Scepter",
    "9sc": "Rune Scepter",
    "9qs": "Holy Water Sprinkler",
    "9ja": "War Javelin",
    "9pi": "Great Pilum",
    "9ts": "Harpoon",
    "7sc": "Mighty Scepter",
    "7qs": "Seraph Rod",
    "7ja": "Hyperion Javelin",
    "7pi": "Stygian Pilum",
    "7ts": "Winged Harpoon",
    "flb": "Flamberge",
    "mpi": "Military Pick",
    "ob1": "Eagle Orb",
    "ob2": "Sacred Globe",
    "ob3": "Smoked Sphere",
    "ob4": "Clasped Orb",
    "ob5": "Jared's Stone",
    "ob6": "Glowing Orb",
    "ob7": "Crystalline Globe",
    "ob8": "Cloudy Sphere",
    "ob9": "Sparkling Ball",
    "oba": "Swirling Crystal",
    "obb": "Heavenly Stone",
    "obc": "Eldritch Orb",
    "obd": "Demon Heart",
    "obe": "Vortex Orb",
    "obf": "Dimensional Shard",

    # ── Amazon Weapons ──────────────────────────────────────────────
    "am1": "Stag Bow",
    "am2": "Reflex Bow",
    "am3": "Maiden Spear",
    "am4": "Maiden Pike",
    "am5": "Maiden Javelin",
    "am6": "Ashwood Bow",
    "am7": "Ceremonial Bow",
    "am8": "Ceremonial Spear",
    "am9": "Ceremonial Pike",
    "ama": "Ceremonial Javelin",
    "amb": "Matriarchal Bow",
    "amc": "Grand Matron Bow",
    "amd": "Matriarchal Spear",
    "ame": "Matriarchal Pike",
    "amf": "Matriarchal Javelin",

    # ── Barbarian Helms ─────────────────────────────────────────────
    "ba1": "Jawbone Cap",
    "ba2": "Fanged Helm",
    "ba3": "Horned Helm",
    "ba4": "Assault Helmet",
    "ba5": "Avenger Guard",
    "ba6": "Jawbone Visor",
    "ba7": "Lion Helm",
    "ba8": "Rage Mask",
    "ba9": "Savage Helmet",
    "baa": "Slayer Guard",
    "bab": "Carnage Helm",
    "bac": "Fury Visor",
    "bad": "Destroyer Helm",
    "bae": "Conqueror Crown",
    "baf": "Guardian Crown",

    # ── Druid Pelts ─────────────────────────────────────────────────
    "dr1": "Wolf Head",
    "dr2": "Hawk Helm",
    "dr3": "Antlers",
    "dr4": "Falcon Mask",
    "dr5": "Spirit Mask",
    "dr6": "Alpha Helm",
    "dr7": "Griffon Headress",
    "dr8": "Hunter's Guise",
    "dr9": "Sacred Feathers",
    "dra": "Totemic Mask",
    "drb": "Blood Spirit",
    "drc": "Sun Spirit",
    "drd": "Earth Spirit",
    "dre": "Sky Spirit",
    "drf": "Dream Spirit",

    # ── Necro Heads ─────────────────────────────────────────────────
    "ne1": "Preserved Head",
    "ne2": "Zombie Head",
    "ne3": "Unraveller Head",
    "ne4": "Gargoyle Head",
    "ne5": "Demon Head",
    "ne6": "Mummified Trophy",
    "ne7": "Fetish Trophy",
    "ne8": "Sexton Trophy",
    "ne9": "Cantor Trophy",
    "nea": "Heirophant Trophy",
    "neb": "Minion Skull",
    "ned": "Overseer Skull",
    "nee": "Succubus Skull",
    "nef": "Bloodlord Skull",
    "neg": "Hellspawn Skull",

    # ── Paladin Shields ─────────────────────────────────────────────
    "pa1": "Targe",
    "pa2": "Rondache",
    "pa3": "Heraldic Shield",
    "pa4": "Aerin Shield",
    "pa5": "Crown Shield",
    "pa6": "Akaran Targe",
    "pa7": "Akaran Rondache",
    "pa8": "Protector Shield",
    "pa9": "Gilded Shield",
    "paa": "Royal Shield",
    "pab": "Sacred Targe",
    "pac": "Sacred Rondache",
    "pad": "Ancient Shield",
    "pae": "Zakarum Shield",
    "paf": "Vortex Shield",

    # ── Circlets ────────────────────────────────────────────────────
    "ci0": "Circlet",
    "ci1": "Coronet",
    "ci2": "Tiara",
    "ci3": "Diadem",

    # ── Armor: Shields (missing) ────────────────────────────────────
    "spk": "Spiked Shield",
    "bsh": "Bone Shield",
    "xpk": "Barbed Shield",
    "xsh": "Grim Shield",
    "xit": "Dragon Shield",
    "uit": "Monarch",
    "upk": "Blade Barrier",
    "ush": "Troll Nest",
    "urg": "Hyperion",

    # ── Armor: Exc/Elite Gloves ─────────────────────────────────────
    "xvg": "Sharkskin Gloves",
    "xmg": "Heavy Bracers",
    "xtg": "Battle Gauntlets",
    "xhg": "War Gauntlets",
    "uvg": "Vampirebone Gloves",
    "umg": "Vambraces",
    "utg": "Crusader Gauntlets",
    "uhg": "Ogre Gauntlets",

    # ── Armor: Exc/Elite Boots ──────────────────────────────────────
    "xlb": "Demonhide Boots",
    "xvb": "Sharkskin Boots",
    "xmb": "Mesh Boots",
    "xtb": "Battle Boots",
    "xhb": "War Boots",
    "ulb": "Wyrmhide Boots",
    "uvb": "Scarabshell Boots",
    "umb": "Boneweave Boots",
    "utb": "Mirrored Boots",
    "uhb": "Myrmidon Greaves",

    # ── Armor: Exc/Elite Belts ──────────────────────────────────────
    "zlb": "Demonhide Sash",
    "zvb": "Sharkskin Belt",
    "zmb": "Mesh Belt",
    "ztb": "Battle Belt",
    "zhb": "War Belt",
    "ulc": "Spiderweb Sash",
    "uvc": "Vampirefang Belt",
    "umc": "Mithril Coil",
    "utc": "Troll Belt",
    "uhc": "Colossus Girdle",
    "lbl": "Sash",

    # ── Armor: Misc Missing ─────────────────────────────────────────
    "aar": "Ancient Armor",
    "bhm": "Bone Helm",
    "xh9": "Grim Helm",
    "uh9": "Bone Visage",
    "utp": "Archon Plate",

    # ── Misc items in stash ─────────────────────────────────────────
    "cjw": "Colossal Jewel",
    "glg": "Flawless Emerald",

    # ── Other missing items ────────────────────────────────────────
    "7br": "Mancatcher",
    "7gw": "Unearthed Wand",
    "7kr": "Fanged Knife",
    "7mp": "War Spike",
    "7s7": "Balrog Spear",
    "92a": "Twin Axe",
    "92h": "Espandon",
    "9br": "War Fork",
    "9cr": "Dimensional Blade",
    "9gd": "Executioner Sword",
    "9gw": "Grave Wand",
    "9kr": "Cinquedeas",
    "9mp": "Crowbill",
    "9s9": "Simbilan",
    "9tw": "Greater Talons",
    "9vo": "Bill",
    "9wb": "Wrist Spike",
    "cs2": "Crafted Sunder Charm",
    "qf2": "Khalim's Will",
    "wsd": "War Sword",
    "xrg": "Scutum",
    "xtp": "Mage Plate",
    # ── Reign of the Warlock patch ──────────────────────────────────────────
    "wac": "Occult Tome",
}
