"""
Item stat bit-width table for property list skipping.

STAT_WIDTHS maps stat_id → total bits to consume per stat entry
  = save_param_bits + save_bits
Used by skip_properties() to advance past the property list to the 0x1FF sentinel.

Format of source data: stat_id → (save_bits, save_add, save_param_bits)
STAT_WIDTHS pre-computes save_param_bits + save_bits for each entry.

Auto-generated by scripts/generate_stat_table.py from data/tmp/excel/itemstatcost.txt
with empirical D2R overrides applied on top.
"""
from __future__ import annotations

# (save_bits, save_add, save_param_bits) for each stat_id.
# Preserved for any code that needs raw widths or save_add.
STAT_TABLE: dict[int, tuple[int, int, int]] = {
    0:     ( 8,  32,  0),   # strength
    1:     ( 7,  32,  0),   # energy
    2:     ( 7,  32,  0),   # dexterity
    3:     ( 7,  32,  0),   # vitality
    4:     ( 7,   0,  0),   # D2R override: statpts, D2R confirmed save_bits=7 empirically from Goldwrap parsing
    5:     ( 8,   0,  0),   # D2R override: newskills, D2R save_bits=8; appears on unique shields
    6:     ( 8,   0,  0),   # D2R override: hitpoints, D2R save_bits=8; appears on unique swords/shields
    7:     ( 9,  32,  0),   # maxhp
    8:     ( 9,   0,  0),   # D2R override: mana, D2R empirically determined
    9:     ( 8,  32,  0),   # maxmana
    10:    ( 1,   0,  0),   # D2R override: D2R stat 10, empirically determined header stat on some charms
    11:    ( 8,  32,  0),   # maxstamina
    12:    ( 9,   0,  0),   # D2R override: D2R stat 12, empirically determined
    14:    ( 9,   0,  0),   # D2R override: D2R stat 14, empirically determined; appears after stat 30 on gloves
    15:    ( 3,   0,  0),   # D2R override: D2R stat 15, confirmed save_bits=3 (only 3 bits remain)
    16:    ( 9,   0,  0),   # item_armor_percent
    17:    ( 9,   0,  0),   # item_maxdamage_percent
    18:    ( 9,   0,  0),   # item_mindamage_percent
    19:    (10,   0,  0),   # tohit
    20:    ( 6,   0,  0),   # toblock
    21:    ( 6,   0,  0),   # mindamage
    22:    ( 7,   0,  0),   # maxdamage
    23:    ( 6,   0,  0),   # secondary_mindamage
    24:    ( 7,   0,  0),   # secondary_maxdamage
    25:    ( 8,   0,  0),   # damagepercent
    26:    ( 8,   0,  0),   # manarecovery
    27:    ( 8,   0,  0),   # manarecoverybonus
    28:    ( 8,   0,  0),   # staminarecoverybonus
    30:    ( 3,   0,  0),   # D2R override: D2R stat 30, confirmed save_bits=3; header stat on belts/gloves/boots
    31:    (11,  10,  0),   # armorclass
    32:    ( 9,   0,  0),   # armorclass_vs_missile
    33:    ( 8,   0,  0),   # armorclass_vs_hth
    34:    ( 6,   0,  0),   # normal_damage_reduction
    35:    ( 6,   0,  0),   # magic_damage_reduction
    36:    ( 9, 200,  0),   # damageresist
    37:    ( 9, 200,  0),   # magicresist
    38:    ( 5,   0,  0),   # maxmagicresist
    39:    ( 9, 200,  0),   # fireresist
    40:    ( 5,   0,  0),   # maxfireresist
    41:    ( 9, 200,  0),   # lightresist
    42:    ( 5,   0,  0),   # maxlightresist
    43:    ( 9, 200,  0),   # coldresist
    44:    ( 5,   0,  0),   # maxcoldresist
    45:    ( 9, 200,  0),   # poisonresist
    46:    ( 5,   0,  0),   # maxpoisonresist
    48:    ( 8,   0,  0),   # firemindam
    49:    ( 9,   0,  0),   # firemaxdam
    50:    ( 6,   0,  0),   # lightmindam
    51:    (10,   0,  0),   # lightmaxdam
    52:    ( 8,   0,  0),   # magicmindam
    53:    ( 9,   0,  0),   # magicmaxdam
    54:    ( 8,   0,  0),   # coldmindam
    55:    ( 9,   0,  0),   # coldmaxdam
    56:    ( 8,   0,  0),   # coldlength
    57:    (10,   0,  0),   # poisonmindam
    58:    (10,   0,  0),   # poisonmaxdam
    59:    ( 9,   0,  0),   # poisonlength
    60:    ( 7,   0,  0),   # lifedrainmindam
    62:    ( 7,   0,  0),   # manadrainmindam
    64:    (12,   0,  0),   # D2R override: stamdrainmindam, empirical; data file has empty Save Bits
    65:    ( 7,   0,  0),   # D2R override: stamdrainmaxdam, empirical
    66:    ( 8,   0,  0),   # D2R override: stunlength, empirical
    67:    ( 7,  30,  0),   # velocitypercent
    68:    ( 7,  30,  0),   # attackrate
    69:    ( 8,   0,  0),   # D2R override: unknown stat 69, empirical
    71:    ( 8, 100,  0),   # value
    72:    ( 9,   0,  0),   # durability
    73:    ( 8,   0,  0),   # maxdurability
    74:    ( 6,  30,  0),   # hpregen
    75:    ( 7,  20,  0),   # item_maxdurability_percent
    76:    ( 6,  10,  0),   # item_maxhp_percent
    77:    ( 6,  10,  0),   # item_maxmana_percent
    78:    ( 7,   0,  0),   # item_attackertakesdamage
    79:    ( 9, 100,  0),   # item_goldbonus
    80:    ( 8, 100,  0),   # item_magicbonus
    81:    ( 7,   0,  0),   # item_knockback
    82:    ( 9,  20,  0),   # item_timeduration
    83:    ( 3,   0,  3),   # item_addclassskills
    84:    ( 3,   0,  0),   # D2R override: D2R stat 84, empirically determined save_bits=3; header on some armor
    85:    ( 9,  50,  0),   # item_addexperience
    86:    ( 7,   0,  0),   # item_healafterkill
    87:    ( 7,   0,  0),   # item_reducedprices
    88:    ( 1,   0,  0),   # item_doubleherbduration
    89:    ( 4,   4,  0),   # item_lightradius
    90:    (24,   0,  0),   # item_lightcolor
    91:    ( 8, 100,  0),   # item_req_percent
    92:    ( 7,   0,  0),   # item_levelreq
    93:    ( 7,  20,  0),   # item_fasterattackrate
    94:    ( 7,  64,  0),   # item_levelreqpct
    96:    ( 7,  20,  0),   # item_fastermovevelocity
    97:    ( 6,   0,  9),   # item_nonclassskill
    98:    ( 1,   0,  8),   # state
    99:    ( 7,  20,  0),   # item_fastergethitrate
    100:   ( 8,   0,  0),   # D2R override: D2R stat 100, save_bits=8; appears on unique weapons
    101:   ( 8,   0,  0),   # D2R override: unknown stat 101, empirical
    102:   ( 7,  20,  0),   # item_fasterblockrate
    103:   ( 8,   0,  0),   # D2R override: D2R stat 103, save_bits=8; appears on rare armor items
    105:   ( 7,  20,  0),   # item_fastercastrate
    107:   ( 3,   0,  9),   # item_singleskill
    108:   ( 1,   0,  0),   # item_restinpeace
    109:   ( 9,   0,  0),   # curse_resistance
    110:   ( 8,  20,  0),   # item_poisonlengthresist
    111:   ( 9,  20,  0),   # item_normaldamage
    112:   ( 7,  -1,  0),   # item_howl
    113:   ( 7,   0,  0),   # item_stupidity
    114:   ( 6,   0,  0),   # item_damagetomana
    115:   ( 1,   0,  0),   # item_ignoretargetac
    116:   ( 7,   0,  0),   # item_fractionaltargetac
    117:   ( 7,   0,  0),   # item_preventheal
    118:   ( 1,   0,  0),   # item_halffreezeduration
    119:   ( 9,  20,  0),   # item_tohit_percent
    120:   ( 7, 128,  0),   # item_damagetargetac
    121:   ( 9,  20,  0),   # item_demondamage_percent
    122:   ( 9,  20,  0),   # item_undeaddamage_percent
    123:   (10, 128,  0),   # item_demon_tohit
    124:   (10, 128,  0),   # item_undead_tohit
    125:   ( 1,   0,  0),   # item_throwable
    126:   ( 3,   0,  3),   # item_elemskill
    127:   ( 3,   0,  0),   # item_allskills
    128:   ( 5,   0,  0),   # item_attackertakeslightdamage
    129:   ( 8,   0,  0),   # D2R override: D2R stat 129, save_bits=8; appears on magic amulets
    130:   ( 8,   0,  0),   # D2R override: D2R stat 130, save_bits=8; appears on rare helms
    131:   (11,   0,  0),   # D2R override: D2R stat 131, CONFIRMED save_bits=11 (leads to sentinel)
    134:   ( 5,   0,  0),   # item_freeze
    135:   ( 7,   0,  0),   # item_openwounds
    136:   ( 7,   0,  0),   # item_crushingblow
    137:   ( 7,   0,  0),   # item_kickdamage
    138:   ( 7,   0,  0),   # item_manaafterkill
    139:   ( 7,   0,  0),   # item_healafterdemonkill
    140:   ( 7,   0,  0),   # item_extrablood
    141:   ( 7,   0,  0),   # item_deadlystrike
    142:   ( 7,   0,  0),   # item_absorbfire_percent
    143:   ( 7,   0,  0),   # item_absorbfire
    144:   ( 7,   0,  0),   # item_absorblight_percent
    145:   ( 7,   0,  0),   # item_absorblight
    146:   ( 7,   0,  0),   # item_absorbmagic_percent
    147:   ( 7,   0,  0),   # item_absorbmagic
    148:   ( 7,   0,  0),   # item_absorbcold_percent
    149:   ( 7,   0,  0),   # item_absorbcold
    150:   ( 7,   0,  0),   # item_slow
    151:   ( 5,   0,  9),   # item_aura
    152:   ( 1,   0,  0),   # item_indesctructible
    153:   ( 1,   0,  0),   # item_cannotbefrozen
    154:   ( 7,  20,  0),   # item_staminadrainpct
    155:   ( 7,   0, 10),   # item_reanimate
    156:   ( 7,   0,  0),   # item_pierce
    157:   ( 7,   0,  0),   # item_magicarrow
    158:   ( 7,   0,  0),   # item_explosivearrow
    159:   ( 6,   0,  0),   # item_throw_mindamage
    160:   ( 7,   0,  0),   # item_throw_maxdamage
    161:   ( 8,   0,  0),   # D2R override: unknown stat 161, empirical
    166:   ( 8,   0,  0),   # D2R override: D2R stat 166, save_bits=8; appears on rare jewelry
    169:   ( 8,   0,  0),   # D2R override: unknown stat 169, empirical
    172:   ( 2,   0,  0),   # D2R override: alignment, empirical
    173:   ( 8,   0,  0),   # D2R override: target0, empirical
    174:   ( 8,   0,  0),   # D2R override: target1, empirical
    175:   ( 8,   0,  0),   # D2R override: unknown stat 175, empirical
    176:   ( 8,   0,  0),   # D2R override: conversion_level, empirical
    177:   ( 8,   0,  0),   # D2R override: conversion_maxhp, empirical
    178:   ( 8,   0,  0),   # D2R override: unit_dooverlay, empirical
    179:   ( 9,   0, 10),   # attack_vs_montype
    180:   ( 9,   0, 10),   # damage_vs_montype
    181:   ( 3,   0,  0),   # fade
    182:   ( 8,   0,  0),   # D2R override: armor_override_percent, empirical
    183:   ( 8,   0,  0),   # D2R override: lasthitreactframe, empirical
    184:   ( 8,   0,  0),   # D2R override: create_season, empirical
    185:   ( 8,   0,  0),   # bonus_mindamage
    186:   ( 8,   0,  0),   # bonus_maxdamage
    187:   (10,   0,  0),   # item_pierce_cold_immunity
    188:   ( 3,   0, 16),   # item_addskill_tab
    189:   (10,   0,  0),   # item_pierce_fire_immunity
    190:   (10,   0,  0),   # item_pierce_light_immunity
    191:   (10,   0,  0),   # item_pierce_poison_immunity
    192:   (10,   0,  0),   # item_pierce_damage_immunity
    193:   (10,   0,  0),   # item_pierce_magic_immunity
    194:   ( 4,   0,  0),   # item_numsockets
    195:   ( 7,   0, 16),   # item_skillonattack
    196:   ( 7,   0, 16),   # item_skillonkill
    197:   ( 7,   0, 16),   # item_skillondeath
    198:   ( 7,   0, 16),   # item_skillonhit
    199:   ( 7,   0, 16),   # item_skillonlevelup
    200:   ( 7,   0,  0),   # item_charge_noconsume
    201:   ( 7,   0, 16),   # item_skillongethit
    204:   (16,   0, 16),   # item_charged_skill
    205:   ( 7,   0,  0),   # item_noconsume
    206:   ( 8,   0,  0),   # passive_mastery_noconsume
    207:   ( 8,   0,  0),   # passive_mastery_replenish_oncrit
    210:   ( 8,   0,  0),   # D2R override: D2R stat 210, save_bits=8; appears on rare rings/jewelry
    211:   ( 8,   0,  0),   # D2R override: ua_defeated counter, empirical
    212:   ( 8,   0,  0),   # D2R override: unknown stat 212, empirical
    213:   ( 8,   0,  0),   # passive_mastery_attack_speed
    214:   ( 6,   0,  0),   # item_armor_perlevel
    215:   ( 6,   0,  0),   # item_armorpercent_perlevel
    216:   ( 6,   0,  0),   # item_hp_perlevel
    217:   ( 6,   0,  0),   # item_mana_perlevel
    218:   ( 6,   0,  0),   # item_maxdamage_perlevel
    219:   ( 6,   0,  0),   # item_maxdamage_percent_perlevel
    220:   ( 6,   0,  0),   # item_strength_perlevel
    221:   ( 6,   0,  0),   # item_dexterity_perlevel
    222:   ( 6,   0,  0),   # item_energy_perlevel
    223:   ( 6,   0,  0),   # item_vitality_perlevel
    224:   ( 6,   0,  0),   # item_tohit_perlevel
    225:   ( 6,   0,  0),   # item_tohitpercent_perlevel
    226:   ( 6,   0,  0),   # item_cold_damagemax_perlevel
    227:   ( 6,   0,  0),   # item_fire_damagemax_perlevel
    228:   ( 6,   0,  0),   # item_ltng_damagemax_perlevel
    229:   ( 6,   0,  0),   # item_pois_damagemax_perlevel
    230:   ( 6,   0,  0),   # item_resist_cold_perlevel
    231:   ( 6,   0,  0),   # item_resist_fire_perlevel
    232:   ( 6,   0,  0),   # item_resist_ltng_perlevel
    233:   ( 6,   0,  0),   # item_resist_pois_perlevel
    234:   ( 6,   0,  0),   # item_absorb_cold_perlevel
    235:   ( 6,   0,  0),   # item_absorb_fire_perlevel
    236:   ( 6,   0,  0),   # item_absorb_ltng_perlevel
    237:   ( 6,   0,  0),   # item_absorb_pois_perlevel
    238:   ( 5,   0,  0),   # item_thorns_perlevel
    239:   ( 6,   0,  0),   # item_find_gold_perlevel
    240:   ( 6,   0,  0),   # item_find_magic_perlevel
    241:   ( 6,   0,  0),   # item_regenstamina_perlevel
    242:   ( 6,   0,  0),   # item_stamina_perlevel
    243:   ( 6,   0,  0),   # item_damage_demon_perlevel
    244:   ( 6,   0,  0),   # item_damage_undead_perlevel
    245:   ( 6,   0,  0),   # item_tohit_demon_perlevel
    246:   ( 6,   0,  0),   # item_tohit_undead_perlevel
    247:   ( 6,   0,  0),   # item_crushingblow_perlevel
    248:   ( 6,   0,  0),   # item_openwounds_perlevel
    249:   ( 6,   0,  0),   # item_kick_damage_perlevel
    250:   ( 6,   0,  0),   # item_deadlystrike_perlevel
    252:   ( 6,   0,  0),   # item_replenish_durability
    253:   ( 6,   0,  0),   # item_replenish_quantity
    254:   ( 8,   0,  0),   # item_extra_stack
    260:   (14,   0,  0),   # D2R override: unknown D2R stat 260, empirical
    268:   (22,   0,  0),   # item_armor_bytime
    269:   (22,   0,  0),   # item_armorpercent_bytime
    270:   (22,   0,  0),   # item_hp_bytime
    271:   (22,   0,  0),   # item_mana_bytime
    272:   (22,   0,  0),   # item_maxdamage_bytime
    273:   (22,   0,  0),   # item_maxdamage_percent_bytime
    274:   (22,   0,  0),   # item_strength_bytime
    275:   (22,   0,  0),   # item_dexterity_bytime
    276:   (22,   0,  0),   # item_energy_bytime
    277:   (22,   0,  0),   # item_vitality_bytime
    278:   (22,   0,  0),   # item_tohit_bytime
    279:   (22,   0,  0),   # item_tohitpercent_bytime
    280:   (22,   0,  0),   # item_cold_damagemax_bytime
    281:   (22,   0,  0),   # item_fire_damagemax_bytime
    282:   (22,   0,  0),   # item_ltng_damagemax_bytime
    283:   (22,   0,  0),   # item_pois_damagemax_bytime
    284:   (22,   0,  0),   # item_resist_cold_bytime
    285:   (22,   0,  0),   # item_resist_fire_bytime
    286:   (22,   0,  0),   # item_resist_ltng_bytime
    287:   (22,   0,  0),   # item_resist_pois_bytime
    288:   (22,   0,  0),   # item_absorb_cold_bytime
    289:   (22,   0,  0),   # item_absorb_fire_bytime
    290:   (22,   0,  0),   # item_absorb_ltng_bytime
    291:   (22,   0,  0),   # item_absorb_pois_bytime
    292:   (22,   0,  0),   # item_find_gold_bytime
    293:   (22,   0,  0),   # item_find_magic_bytime
    294:   (22,   0,  0),   # item_regenstamina_bytime
    295:   (22,   0,  0),   # item_stamina_bytime
    296:   (22,   0,  0),   # item_damage_demon_bytime
    297:   (22,   0,  0),   # item_damage_undead_bytime
    298:   (22,   0,  0),   # item_tohit_demon_bytime
    299:   (22,   0,  0),   # item_tohit_undead_bytime
    300:   (22,   0,  0),   # item_crushingblow_bytime
    301:   (22,   0,  0),   # item_openwounds_bytime
    302:   (22,   0,  0),   # item_kick_damage_bytime
    303:   (22,   0,  0),   # item_deadlystrike_bytime
    305:   ( 8,  50,  0),   # item_pierce_cold
    306:   ( 8,  50,  0),   # item_pierce_fire
    307:   ( 8,  50,  0),   # item_pierce_ltng
    308:   ( 8,  50,  0),   # item_pierce_pois
    315:   ( 8,   0,  0),   # D2R override: unknown stat 315, empirical
    316:   ( 8,   0,  0),   # D2R override: burningmin, empirical
    317:   ( 9,   0,  0),   # D2R override: burningmax, empirical
    318:   ( 7,   0,  0),   # D2R override: progressive_damage, empirical
    319:   ( 7,   0,  0),   # D2R override: progressive_steal, empirical
    320:   ( 7,   0,  0),   # D2R override: progressive_other, empirical
    321:   ( 7,   0,  0),   # D2R override: progressive_fire, empirical
    322:   ( 7,   0,  0),   # D2R override: progressive_cold, empirical
    323:   ( 7,   0,  0),   # D2R override: progressive_lightning, empirical
    324:   ( 6,   0,  0),   # item_extra_charges
    325:   ( 7,   0,  0),   # D2R override: progressive_tohit, empirical
    326:   ( 5,   0,  0),   # D2R override: poison_count, empirical
    327:   ( 8,   0,  0),   # D2R override: damage_framerate, empirical
    328:   ( 8,   0,  0),   # D2R override: pierce_idx, empirical
    329:   ( 9,  50,  0),   # passive_fire_mastery
    330:   ( 9,  50,  0),   # passive_ltng_mastery
    331:   ( 9,  50,  0),   # passive_cold_mastery
    332:   ( 9,  50,  0),   # passive_pois_mastery
    333:   ( 8,   0,  0),   # passive_fire_pierce
    334:   ( 8,   0,  0),   # passive_ltng_pierce
    335:   ( 8,   0,  0),   # passive_cold_pierce
    336:   ( 8,   0,  0),   # passive_pois_pierce
    337:   ( 8,   0,  0),   # passive_critical_strike
    338:   ( 7,   0,  0),   # passive_dodge
    339:   ( 7,   0,  0),   # passive_avoid
    340:   ( 7,   0,  0),   # passive_evade
    341:   ( 8,   0,  0),   # passive_warmth
    342:   ( 8,   0,  0),   # passive_mastery_melee_th
    343:   ( 8,   0,  0),   # passive_mastery_melee_dmg
    344:   ( 8,   0,  0),   # passive_mastery_melee_crit
    345:   ( 8,   0,  0),   # passive_mastery_throw_th
    346:   ( 8,   0,  0),   # passive_mastery_throw_dmg
    347:   ( 8,   0,  0),   # passive_mastery_throw_crit
    348:   ( 8,   0,  0),   # passive_weaponblock
    349:   ( 8,   0,  0),   # passive_summon_resist
    353:   ( 8,   0,  0),   # D2R override: D2R stat 353, save_bits=8; appears on unique boots
    356:   ( 2,   0,  0),   # questitemdifficulty
    357:   ( 9,  50,  0),   # passive_mag_mastery
    358:   ( 8,   0,  0),   # passive_mag_pierce
    363:   ( 8,   0,  0),   # D2R override: unknown stat 363, empirical
    364:   ( 8,   0,  0),   # D2R override: customization_index, empirical
    365:   ( 6,   0,  0),   # item_magic_damagemax_perlevel
    366:   ( 8,   0,  0),   # passive_dmg_pierce
    368:   ( 8,   0,  0),   # D2R additions 368-395
    369:   ( 8,   0,  0),   # D2R additions 368-395
    370:   ( 8,   0,  0),   # D2R additions 368-395
    371:   ( 8,   0,  0),   # D2R additions 368-395
    372:   ( 8,   0,  0),   # D2R additions 368-395
    373:   ( 8,   0,  0),   # D2R additions 368-395
    374:   ( 8,   0,  0),   # D2R additions 368-395
    375:   ( 8,   0,  0),   # D2R additions 368-395
    376:   ( 8,   0,  0),   # D2R additions 368-395
    377:   ( 8,   0,  0),   # D2R additions 368-395
    378:   ( 8,   0,  0),   # D2R additions 368-395
    379:   ( 8,   0,  0),   # D2R additions 368-395
    380:   ( 8,   0,  0),   # D2R additions 368-395
    381:   ( 8,   0,  0),   # D2R additions 368-395
    382:   ( 8,   0,  0),   # D2R additions 368-395
    383:   ( 8,   0,  0),   # D2R additions 368-395
    384:   ( 8,   0,  0),   # D2R additions 368-395
    385:   ( 8, 237,  0),   # D2R override: mod extra gold from monsters
    386:   ( 8,   0,  0),   # D2R additions 368-395
    387:   ( 8,   0,  0),   # D2R additions 368-395
    388:   ( 8,   0,  0),   # D2R additions 368-395
    389:   ( 8,   0,  0),   # D2R additions 368-395
    390:   ( 8,   0,  0),   # D2R additions 368-395
    391:   ( 8,   0,  0),   # D2R additions 368-395
    392:   ( 8,   0,  0),   # D2R additions 368-395
    393:   ( 8,   0,  0),   # D2R additions 368-395
    394:   ( 8,   0,  0),   # D2R additions 368-395
    395:   ( 8,   0,  0),   # D2R additions 368-395
    396:   ( 0,   0,  0),   # unknown D2R flag
    397:   ( 8,   0,  0),   # D2R additions 397-423
    398:   ( 8,   0,  0),   # D2R additions 397-423
    399:   ( 8,   0,  0),   # D2R additions 397-423
    400:   ( 8,   0,  0),   # D2R additions 397-423
    401:   ( 8,   0,  0),   # D2R additions 397-423
    402:   ( 8,   0,  0),   # D2R additions 397-423
    403:   ( 8,   0,  0),   # D2R additions 397-423
    404:   ( 8,   0,  0),   # D2R additions 397-423
    405:   ( 8,   0,  0),   # D2R additions 397-423
    406:   ( 8,   0,  0),   # D2R additions 397-423
    407:   ( 8,   0,  0),   # D2R additions 397-423
    408:   ( 8,   0,  0),   # D2R additions 397-423
    409:   ( 8,   0,  0),   # D2R additions 397-423
    410:   ( 8,   0,  0),   # D2R additions 397-423
    411:   ( 8,   0,  0),   # D2R additions 397-423
    412:   ( 8,   0,  0),   # D2R additions 397-423
    413:   ( 8,   0,  0),   # D2R additions 397-423
    414:   ( 8,   0,  0),   # D2R additions 397-423
    415:   ( 8,   0,  0),   # D2R additions 397-423
    416:   ( 8,   0,  0),   # D2R additions 397-423
    417:   ( 8,   0,  0),   # D2R additions 397-423
    418:   ( 8,   0,  0),   # D2R additions 397-423
    419:   ( 8,   0,  0),   # D2R additions 397-423
    420:   ( 8,   0,  0),   # D2R additions 397-423
    421:   ( 8,   0,  0),   # D2R additions 397-423
    422:   ( 8,   0,  0),   # D2R additions 397-423
    423:   ( 8,   0,  0),   # D2R additions 397-423
    424:   ( 0,   0,  0),   # unknown D2R flag
    425:   ( 8,   0,  0),   # D2R additions 425-510
    426:   ( 8,   0,  0),   # D2R additions 425-510
    427:   ( 8,   0,  0),   # D2R additions 425-510
    428:   ( 8,   0,  0),   # D2R additions 425-510
    429:   ( 8,   0,  0),   # D2R additions 425-510
    430:   ( 8,   0,  0),   # D2R additions 425-510
    431:   ( 8,   0,  0),   # D2R additions 425-510
    432:   ( 8,   0,  0),   # D2R additions 425-510
    433:   ( 8,   0,  0),   # D2R additions 425-510
    434:   ( 8,   0,  0),   # D2R additions 425-510
    435:   ( 8,   0,  0),   # D2R additions 425-510
    436:   ( 8,   0,  0),   # D2R additions 425-510
    437:   ( 8,   0,  0),   # D2R additions 425-510
    438:   ( 8,   0,  0),   # D2R additions 425-510
    439:   ( 8,   0,  0),   # D2R additions 425-510
    440:   ( 8,   0,  0),   # D2R additions 425-510
    441:   ( 8,   0,  0),   # D2R additions 425-510
    442:   ( 8,   0,  0),   # D2R additions 425-510
    443:   ( 8,   0,  0),   # D2R additions 425-510
    444:   ( 8,   0,  0),   # D2R additions 425-510
    445:   ( 8,   0,  0),   # D2R additions 425-510
    446:   ( 8,   0,  0),   # D2R additions 425-510
    447:   ( 8,   0,  0),   # D2R additions 425-510
    448:   ( 8,   0,  0),   # D2R additions 425-510
    449:   ( 8,   0,  0),   # D2R additions 425-510
    450:   ( 8,   0,  0),   # D2R additions 425-510
    451:   ( 8,   0,  0),   # D2R additions 425-510
    452:   ( 8,   0,  0),   # D2R additions 425-510
    453:   ( 8,   0,  0),   # D2R additions 425-510
    454:   ( 8,   0,  0),   # D2R additions 425-510
    455:   ( 8,   0,  0),   # D2R additions 425-510
    456:   ( 8,   0,  0),   # D2R additions 425-510
    457:   ( 4,   0,  0),   # D2R override: Reign of the Warlock patch stat, confirmed save_bits=4
    458:   ( 8,   0,  0),   # D2R additions 425-510
    459:   ( 8,   0,  0),   # D2R additions 425-510
    460:   ( 8,   0,  0),   # D2R additions 425-510
    461:   ( 8,   0,  0),   # D2R additions 425-510
    462:   ( 8,   0,  0),   # D2R additions 425-510
    463:   ( 8,   0,  0),   # D2R additions 425-510
    464:   ( 8,   0,  0),   # D2R additions 425-510
    465:   ( 8,   0,  0),   # D2R additions 425-510
    466:   ( 8,   0,  0),   # D2R additions 425-510
    467:   ( 8,   0,  0),   # D2R additions 425-510
    468:   ( 8,   0,  0),   # D2R additions 425-510
    469:   ( 8,   0,  0),   # D2R additions 425-510
    470:   ( 8,   0,  0),   # D2R additions 425-510
    471:   ( 8,   0,  0),   # D2R additions 425-510
    472:   ( 8,   0,  0),   # D2R additions 425-510
    473:   ( 8,   0,  0),   # D2R additions 425-510
    474:   ( 8,   0,  0),   # D2R additions 425-510
    475:   ( 8,   0,  0),   # D2R additions 425-510
    476:   ( 8,   0,  0),   # D2R additions 425-510
    477:   ( 8,   0,  0),   # D2R additions 425-510
    478:   ( 8,   0,  0),   # D2R additions 425-510
    479:   ( 8,   0,  0),   # D2R additions 425-510
    480:   ( 8,   0,  0),   # D2R additions 425-510
    481:   ( 8,   0,  0),   # D2R additions 425-510
    482:   ( 8,   0,  0),   # D2R additions 425-510
    483:   ( 8,   0,  0),   # D2R additions 425-510
    484:   ( 8,   0,  0),   # D2R additions 425-510
    485:   ( 8,   0,  0),   # D2R additions 425-510
    486:   ( 8,   0,  0),   # D2R additions 425-510
    487:   ( 8,   0,  0),   # D2R additions 425-510
    488:   ( 8,   0,  0),   # D2R additions 425-510
    489:   ( 8,   0,  0),   # D2R additions 425-510
    490:   ( 8,   0,  0),   # D2R additions 425-510
    491:   ( 8,   0,  0),   # D2R additions 425-510
    492:   ( 8,   0,  0),   # D2R additions 425-510
    493:   ( 8,   0,  0),   # D2R additions 425-510
    494:   ( 8,   0,  0),   # D2R additions 425-510
    495:   ( 8,   0,  0),   # D2R additions 425-510
    496:   ( 8,   0,  0),   # D2R additions 425-510
    497:   ( 8,   0,  0),   # D2R additions 425-510
    498:   ( 8,   0,  0),   # D2R additions 425-510
    499:   ( 8,   0,  0),   # D2R additions 425-510
    500:   ( 8,   0,  0),   # D2R additions 425-510
    501:   ( 8,   0,  0),   # D2R additions 425-510
    502:   ( 8,   0,  0),   # D2R additions 425-510
    503:   ( 8,   0,  0),   # D2R additions 425-510
    504:   ( 8,   0,  0),   # D2R additions 425-510
    505:   ( 8,   0,  0),   # D2R additions 425-510
    506:   ( 8,   0,  0),   # D2R additions 425-510
    507:   ( 8,   0,  0),   # D2R additions 425-510
    508:   ( 8,   0,  0),   # D2R additions 425-510
    509:   ( 8,   0,  0),   # D2R additions 425-510
    510:   ( 8,   0,  0),   # D2R additions 425-510
}

# Derived: stat_id → total bits to consume (save_param_bits + save_bits)
STAT_WIDTHS: dict[int, int] = {
    sid: (bits[2] + bits[0]) for sid, bits in STAT_TABLE.items()
}

# Stat IDs that are character/entity values — cannot legitimately appear in
# an item property list. Seeing one signals a mis-detected quality offset.
PROPERTY_BLOCKLIST: frozenset[int] = frozenset(
    {4, 5, 6, 8, 10, 12, 13, 14, 15, 29, 30, 353, 354}
)
