"""
Unique and set item name lookup tables.

Generated from D2R data files by scripts/generate_unique_set_names.py.
Maps unique_id/set_id → display name for use as fallback in item_names.resolve_name().
"""
from __future__ import annotations

UNIQUE_NAMES: dict[int, str] = {
    0: "The Gnasher",
    1: "Deathspade",
    2: "Bladebone",
    3: "Mindrend",
    4: "Rakescar",
    5: "Fechmars Axe",
    6: "Goreshovel",
    7: "The Chieftan",
    8: "Brainhew",
    9: "The Humongous",
    10: "Iros Torch",
    11: "Maelstromwrath",
    12: "Gravenspine",
    13: "Umes Lament",
    14: "Felloak",
    15: "Knell Striker",
    16: "Rusthandle",
    17: "Stormeye",
    18: "Stoutnail",
    19: "Crushflange",
    20: "Bloodrise",
    21: "The Generals Tan Do Li Ga",
    22: "Ironstone",
    23: "Bonesob",
    24: "Steeldriver",
    25: "Rixots Keen",
    26: "Blood Crescent",
    27: "Krintizs Skewer",
    28: "Gleamscythe",
    29: "Azurewrath",
    30: "Griswolds Edge",
    31: "Hellplague",
    32: "Culwens Point",
    33: "Shadowfang",
    34: "Soulflay",
    35: "Kinemils Awl",
    36: "Blacktongue",
    37: "Ripsaw",
    38: "The Patriarch",
    39: "Gull",
    40: "The Diggler",
    41: "The Jade Tan Do",
    42: "Irices Shard",
    43: "The Dragon Chang",
    44: "Razortine",
    45: "Bloodthief",
    46: "Lance of Yaggai",
    47: "The Tannr Gorerod",
    48: "Dimoaks Hew",
    49: "Steelgoad",
    50: "Soul Harvest",
    51: "The Battlebranch",
    52: "Woestave",
    53: "The Grim Reaper",
    54: "Bane Ash",
    55: "Serpent Lord",
    56: "Lazarus Spire",
    57: "The Salamander",
    58: "The Iron Jang Bong",
    59: "Pluckeye",
    60: "Witherstring",
    61: "Rimeraven",
    62: "Piercerib",
    63: "Pullspite",
    64: "Wizendraw",
    65: "Hellclap",
    66: "Blastbark",
    67: "Leadcrow",
    68: "Ichorsting",
    69: "Hellcast",
    70: "Doomspittle",
    71: "War Bonnet",
    72: "Tarnhelm",
    73: "Coif of Glory",
    74: "Duskdeep",
    75: "Wormskull",
    76: "Howltusk",
    77: "Undead Crown",
    78: "The Face of Horror",
    79: "Greyform",
    80: "Blinkbats Form",
    81: "The Centurion",
    82: "Twitchthroe",
    83: "Darkglow",
    84: "Hawkmail",
    85: "Sparking Mail",
    86: "Venomsward",
    87: "Iceblink",
    88: "Boneflesh",
    89: "Rockfleece",
    90: "Rattlecage",
    91: "Goldskin",
    92: "Victors Silk",
    93: "Heavenly Garb",
    94: "Pelta Lunata",
    95: "Umbral Disk",
    96: "Stormguild",
    97: "Wall of the Eyeless",
    98: "Swordback Hold",
    99: "Steelclash",
    100: "Bverrit Keep",
    101: "The Ward",
    102: "The Hand of Broc",
    103: "Bloodfist",
    104: "Chance Guards",
    105: "Magefist",
    106: "Frostburn",
    107: "Hotspur",
    108: "Gorefoot",
    109: "Treads of Cthon",
    110: "Goblin Toe",
    111: "Tearhaunch",
    112: "Lenyms Cord",
    113: "Snakecord",
    114: "Nightsmoke",
    115: "Goldwrap",
    116: "Bladebuckle",
    117: "Nokozan Relic",
    118: "The Eye of Etlich",
    119: "The Mahim-Oak Curio",
    120: "Nagelring",
    121: "Manald Heal",
    122: "The Stone of Jordan",
    123: "Amulet of the Viper",
    124: "Staff of Kings",
    125: "Horadric Staff",
    126: "Hell Forge Hammer",
    127: "KhalimFlail",
    128: "SuperKhalimFlail",
    129: "Coldkill",
    130: "Butcher's Pupil",
    131: "Islestrike",
    132: "Pompe's Wrath",
    133: "Guardian Naga",
    134: "Warlord's Trust",
    135: "Spellsteel",
    136: "Stormrider",
    137: "Boneslayer Blade",
    138: "The Minataur",
    139: "Suicide Branch",
    140: "Carin Shard",
    141: "Arm of King Leoric",
    142: "Blackhand Key",
    143: "Dark Clan Crusher",
    144: "Zakarum's Hand",
    145: "The Fetid Sprinkler",
    146: "Hand of Blessed Light",
    147: "Fleshrender",
    148: "Sureshrill Frost",
    149: "Moonfall",
    150: "Baezil's Vortex",
    151: "Earthshaker",
    152: "Bloodtree Stump",
    153: "The Gavel of Pain",
    154: "Bloodletter",
    155: "Coldsteel Eye",
    156: "Hexfire",
    157: "Blade of Ali Baba",
    158: "Ginther's Rift",
    159: "Headstriker",
    160: "Plague Bearer",
    161: "The Atlantian",
    162: "Crainte Vomir",
    163: "Bing Sz Wang",
    164: "The Vile Husk",
    165: "Cloudcrack",
    166: "Todesfaelle Flamme",
    167: "Swordguard",
    168: "Spineripper",
    169: "Heart Carver",
    170: "Blackbog's Sharp",
    171: "Stormspike",
    172: "The Impaler",
    173: "Kelpie Snare",
    174: "Soulfeast Tine",
    175: "Hone Sundan",
    176: "Spire of Honor",
    177: "The Meat Scraper",
    178: "Blackleach Blade",
    179: "Athena's Wrath",
    180: "Pierre Tombale Couant",
    181: "Husoldal Evo",
    182: "Grim's Burning Dead",
    183: "Razorswitch",
    184: "Ribcracker",
    185: "Chromatic Ire",
    186: "Warpspear",
    187: "Skullcollector",
    188: "Skystrike",
    189: "Riphook",
    190: "Kuko Shakaku",
    191: "Endlesshail",
    192: "Whichwild String",
    193: "Cliffkiller",
    194: "Magewrath",
    195: "Godstrike Arch",
    196: "Langer Briser",
    197: "Pus Spiter",
    198: "Buriza-Do Kyanon",
    199: "Demon Machine",
    201: "Peasent Crown",
    202: "Rockstopper",
    203: "Stealskull",
    204: "Darksight Helm",
    205: "Valkiry Wing",
    206: "Crown of Thieves",
    207: "Blackhorn's Face",
    208: "Vampiregaze",
    209: "The Spirit Shroud",
    210: "Skin of the Vipermagi",
    211: "Skin of the Flayerd One",
    212: "Ironpelt",
    213: "Spiritforge",
    214: "Crow Caw",
    215: "Shaftstop",
    216: "Duriel's Shell",
    217: "Skullder's Ire",
    218: "Guardian Angel",
    219: "Toothrow",
    220: "Atma's Wail",
    221: "Black Hades",
    222: "Corpsemourn",
    223: "Que-Hegan's Wisdon",
    224: "Visceratuant",
    225: "Mosers Blessed Circle",
    226: "Stormchaser",
    227: "Tiamat's Rebuke",
    228: "Kerke's Sanctuary",
    229: "Radimant's Sphere",
    230: "Lidless Wall",
    231: "Lance Guard",
    232: "Venom Grip",
    233: "Gravepalm",
    234: "Ghoulhide",
    235: "Lavagout",
    236: "Hellmouth",
    237: "Infernostride",
    238: "Waterwalk",
    239: "Silkweave",
    240: "Wartraveler",
    241: "Gorerider",
    242: "String of Ears",
    243: "Razortail",
    244: "Gloomstrap",
    245: "Snowclash",
    246: "Thudergod's Vigor",
    248: "Harlequin Crest",
    249: "Veil of Steel",
    250: "The Gladiator's Bane",
    251: "Arkaine's Valor",
    252: "Blackoak Shield",
    253: "Stormshield",
    254: "Hellslayer",
    255: "Messerschmidt's Reaver",
    256: "Baranar's Star",
    257: "Schaefer's Hammer",
    258: "The Cranium Basher",
    259: "Lightsabre",
    260: "Doombringer",
    261: "The Grandfather",
    262: "Wizardspike",
    263: "Constricting Ring",
    264: "Stormspire",
    265: "Eaglehorn",
    266: "Windforce",
    268: "Bul Katho's Wedding Band",
    269: "The Cat's Eye",
    270: "The Rising Sun",
    271: "Crescent Moon",
    272: "Mara's Kaleidoscope",
    273: "Atma's Scarab",
    274: "Dwarf Star",
    275: "Raven Frost",
    276: "Highlord's Wrath",
    277: "Saracen's Chance",
    279: "Arreat's Face",
    280: "Homunculus",
    281: "Titan's Revenge",
    282: "Lycander's Aim",
    283: "Lycander's Flank",
    284: "The Oculus",
    285: "Herald of Zakarum",
    286: "Cutthroat1",
    287: "Jalal's Mane",
    288: "The Scalper",
    289: "Bloodmoon",
    290: "Djinnslayer",
    291: "Deathbit",
    292: "Warshrike",
    293: "Gutsiphon",
    294: "Razoredge",
    295: "Gore Ripper",
    296: "Demonlimb",
    297: "Steelshade",
    298: "Tomb Reaver",
    299: "Deaths's Web",
    300: "Nature's Peace",
    301: "Azurewrath",
    302: "Seraph's Hymn",
    303: "Zakarum's Salvation",
    304: "Fleshripper",
    305: "Odium",
    306: "Horizon's Tornado",
    307: "Stone Crusher",
    308: "Jadetalon",
    309: "Shadowdancer",
    310: "Cerebus",
    311: "Tyrael's Might",
    312: "Souldrain",
    313: "Runemaster",
    314: "Deathcleaver",
    315: "Executioner's Justice",
    316: "Stoneraven",
    317: "Leviathan",
    318: "Larzuk's Champion",
    319: "Wisp",
    320: "Gargoyle's Bite",
    321: "Lacerator",
    322: "Mang Song's Lesson",
    323: "Viperfork",
    324: "Ethereal Edge",
    325: "Demonhorn's Edge",
    326: "The Reaper's Toll",
    327: "Spiritkeeper",
    328: "Hellrack",
    329: "Alma Negra",
    330: "Darkforge Spawn",
    331: "Widowmaker",
    332: "Bloodraven's Charge",
    333: "Ghostflame",
    334: "Shadowkiller",
    335: "Gimmershred",
    336: "Griffon's Eye",
    337: "Windhammer",
    338: "Thunderstroke",
    339: "Giantmaimer",
    340: "Demon's Arch",
    341: "Boneflame",
    342: "Steelpillar",
    343: "Nightwing's Veil",
    344: "Crown of Ages",
    345: "Andariel's Visage",
    346: "Darkfear",
    347: "Dragonscale",
    348: "Steel Carapice",
    349: "Medusa's Gaze",
    350: "Ravenlore",
    351: "Boneshade",
    352: "Nethercrow",
    353: "Flamebellow",
    354: "Fathom",
    355: "Wolfhowl",
    356: "Spirit Ward",
    357: "Kira's Guardian",
    358: "Ormus' Robes",
    359: "Gheed's Fortune",
    360: "Stormlash",
    361: "Halaberd's Reign",
    362: "Warriv's Warder",
    363: "Spike Thorn",
    364: "Dracul's Grasp",
    365: "Frostwind",
    366: "Templar's Might",
    367: "Eschuta's temper",
    368: "Firelizard's Talons",
    369: "Sandstorm Trek",
    370: "Marrowwalk",
    371: "Heaven's Light",
    372: "Merman's Speed",
    373: "Arachnid Mesh",
    374: "Nosferatu's Coil",
    375: "Metalgrid",
    376: "Verdugo's Hearty Cord",
    377: "Sigurd's Staunch",
    378: "Carrion Wind",
    379: "Giantskull",
    380: "Ironward",
    381: "Annihilus",
    382: "Arioc's Needle",
    383: "Cranebeak",
    384: "Nord's Tenderizer",
    385: "Earthshifter",
    386: "Wraithflight",
    387: "Bonehew",
    388: "Ondal's Wisdom",
    389: "The Reedeemer",
    390: "Headhunter's Glory",
    391: "Steelrend",
    392: "Rainbow Facet",
    393: "Rainbow Facet",
    394: "Rainbow Facet",
    395: "Rainbow Facet",
    396: "Rainbow Facet",
    397: "Rainbow Facet",
    398: "Rainbow Facet",
    399: "Rainbow Facet",
    400: "Hellfire Torch",
    401: "Cold Rupture",
    402: "Flame Rift",
    403: "Crack of the Heavens",
    404: "Rotting Fissure",
    405: "Bone Break",
    406: "Black Cleft",
    408: "Ars Al'Diablolos",
    409: "Ars Tor'Baalos",
    410: "Ars Dul'Mephistos",
    411: "Measured Wrath",
    412: "Dreadfang",
    413: "Wraithstep",
    414: "Bloodpact Shard",
    415: "Sling",
    416: "Opalvein",
    417: "Entropy Locket",
    418: "Gheed's Wager",
    419: "Unique Warlock Helm",
    420: "Defender's Bile",
    421: "Guardian's Thunder",
    422: "Protector's Frost",
    423: "Defender's Fire",
    424: "Protector's Stone",
    425: "Guardian's Light",
    426: "PreCrafted Cold Rupture",
    427: "Crafted Cold Rupture",
    428: "PreCrafted Flame Rift",
    429: "PreCrafted Crack of the Heavens",
    430: "PreCrafted Rotting Fissure",
    431: "PreCrafted Bone Break",
    432: "PreCrafted Black Cleft",
    433: "Crafted Flame Rift",
    434: "Crafted Crack of the Heavens",
    435: "Crafted Rotting Fissure",
    436: "Crafted Bone Break",
    437: "Crafted Black Cleft",
}

SET_NAMES: dict[int, str] = {
    0: "Civerb's Ward",
    1: "Civerb's Icon",
    2: "Civerb's Cudgel",
    3: "Hsarus' Iron Heel",
    4: "Hsarus' Iron Fist",
    5: "Hsarus' Iron Stay",
    6: "Cleglaw's Tooth",
    7: "Cleglaw's Claw",
    8: "Cleglaw's Pincers",
    9: "Iratha's Collar",
    10: "Iratha's Cuff",
    11: "Iratha's Coil",
    12: "Iratha's Cord",
    13: "Isenhart's Lightbrand",
    14: "Isenhart's Parry",
    15: "Isenhart's Case",
    16: "Isenhart's Horns",
    17: "Vidala's Barb",
    18: "Vidala's Fetlock",
    19: "Vidala's Ambush",
    20: "Vidala's Snare",
    21: "Milabrega's Orb",
    22: "Milabrega's Rod",
    23: "Milabrega's Diadem",
    24: "Milabrega's Robe",
    25: "Cathan's Rule",
    26: "Cathan's Mesh",
    27: "Cathan's Visage",
    28: "Cathan's Sigil",
    29: "Cathan's Seal",
    30: "Tancred's Crowbill",
    31: "Tancred's Spine",
    32: "Tancred's Hobnails",
    33: "Tancred's Weird",
    34: "Tancred's Skull",
    35: "Sigon's Gage",
    36: "Sigon's Visor",
    37: "Sigon's Shelter",
    38: "Sigon's Sabot",
    39: "Sigon's Wrap",
    40: "Sigon's Guard",
    41: "Infernal Cranium",
    42: "Infernal Torch",
    43: "Infernal Sign",
    44: "Berserker's Headgear",
    45: "Berserker's Hauberk",
    46: "Berserker's Hatchet",
    47: "Death's Hand",
    48: "Death's Guard",
    49: "Death's Touch",
    50: "Angelic Sickle",
    51: "Angelic Mantle",
    52: "Angelic Halo",
    53: "Angelic Wings",
    54: "Arctic Horn",
    55: "Arctic Furs",
    56: "Arctic Binding",
    57: "Arctic Mitts",
    58: "Arcanna's Sign",
    59: "Arcanna's Deathwand",
    60: "Arcanna's Head",
    61: "Arcanna's Flesh",
    62: "Natalya's Totem",
    63: "Natalya's Mark",
    64: "Natalya's Shadow",
    65: "Natalya's Soul",
    66: "Aldur's Stony Gaze",
    67: "Aldur's Deception",
    68: "Aldur's Gauntlet",
    69: "Aldur's Advance",
    70: "Immortal King's Will",
    71: "Immortal King's Soul Cage",
    72: "Immortal King's Detail",
    73: "Immortal King's Forge",
    74: "Immortal King's Pillar",
    75: "Immortal King's Stone Crusher",
    76: "Tal Rasha's Fire-Spun Cloth",
    77: "Tal Rasha's Adjudication",
    78: "Tal Rasha's Lidless Eye",
    79: "Tal Rasha's Howling Wind",
    80: "Tal Rasha's Horadric Crest",
    81: "Griswold's Valor",
    82: "Griswold's Heart",
    83: "Griswolds's Redemption",
    84: "Griswold's Honor",
    85: "Trang-Oul's Guise",
    86: "Trang-Oul's Scales",
    87: "Trang-Oul's Wing",
    88: "Trang-Oul's Claws",
    89: "Trang-Oul's Girth",
    90: "M'avina's True Sight",
    91: "M'avina's Embrace",
    92: "M'avina's Icy Clutch",
    93: "M'avina's Tenet",
    94: "M'avina's Caster",
    95: "Telling of Beads",
    96: "Laying of Hands",
    97: "Rite of Passage",
    98: "Spiritual Custodian",
    99: "Credendum",
    100: "Dangoon's Teaching",
    101: "Heaven's Taebaek",
    102: "Haemosu's Adament",
    103: "Ondal's Almighty",
    104: "Guillaume's Face",
    105: "Wilhelm's Pride",
    106: "Magnus' Skin",
    107: "Wihtstan's Guard",
    108: "Hwanin's Splendor",
    109: "Hwanin's Refuge",
    110: "Hwanin's Seal",
    111: "Hwanin's Justice",
    112: "Sazabi's Cobalt Redeemer",
    113: "Sazabi's Ghost Liberator",
    114: "Sazabi's Mental Sheath",
    115: "Bul-Kathos' Sacred Charge",
    116: "Bul-Kathos' Tribal Guardian",
    117: "Cow King's Horns",
    118: "Cow King's Hide",
    119: "Cow King's Hoofs",
    120: "Naj's Puzzler",
    121: "Naj's Light Plate",
    122: "Naj's Circlet",
    123: "McAuley's Paragon",
    124: "McAuley's Riprap",
    125: "McAuley's Taboo",
    126: "McAuley's Superstition",
    127: "Warlord's Conquest",
    128: "Warlord's Lust",
    129: "Warlord's Mantle",
    130: "Warlord's Crushers",
    131: "Warlord's Authority",
    132: "Bane's Oathmaker",
    133: "Bane's Wraithskin",
    134: "Bane's Authority",
    135: "Horazon's Countenance",
    136: "Horazon's Dominion",
    137: "Horazon's Hold",
    138: "Horazon's Legacy",
    139: "Horazon's Secrets",
}
