"""
Extract static data tables from d2i_parser.py into _d2i_tables.py.

Reads backend/services/d2i_parser.py, extracts all large static data
dictionaries to a new backend/services/_d2i_tables.py, and writes an
updated d2i_parser.py that imports them.

This is a one-time migration script. Run once, verify imports work,
then delete the script.

Usage: python3 scripts/extract_d2i_tables.py
"""

from pathlib import Path

PARSER = Path("backend/services/d2i_parser.py")
TABLES = Path("backend/services/_d2i_tables.py")

# ── Define the data sections to extract ──────────────────────────────────────
# Each entry: (start_line, end_line, name)  — 1-indexed, inclusive
# These are the pure-data blocks (dicts/constants) to move to _d2i_tables.py.
# Functions and non-data constants stay in d2i_parser.py.

# (start, end) are 1-indexed line numbers in the current d2i_parser.py.
DATA_SECTIONS = [
    # Item stat table + Skill names + DMG pairs
    (133, 1099),   # _STAT_TABLE comment, _STAT_TABLE, _SKILL_NAMES, _DMG_PAIRS
    # Modern format constants + Huffman table + MOD_ITEM_NAMES
    (1516, 2094),  # MODERN_* constants, _MOD_*, _HUFFMAN_REVERSE, MOD_ITEM_NAMES
    # Affix name tables section header + _MAGIC_PREFIXES + _MAGIC_SUFFIXES
    (2097, 3572),  # section header, _MAGIC_PREFIXES, _MAGIC_SUFFIXES
    # Charm prefix section comment + tables (not the function)
    (3573, 3661),  # _CHARM_PREFIX_TABLE, _SKILLTAB_PREFIX_NAMES (stop before the function at 3662)
    # Rare prefix/suffix tables (between _lookup_charm_prefix_name and functions)
    (3700, 3908),  # _RARE_PREFIXES, _RARE_SUFFIXES
]

# Import line to add to d2i_parser.py (after the existing imports)
IMPORT_LINE = "from ._d2i_tables import ("
IMPORT_NAMES = [
    "_STAT_TABLE",
    "_SKILL_NAMES",
    "_DMG_PAIRS",
    "MODERN_HEADER_SIZE",
    "MODERN_SEP_SIZE",
    "_MOD_QUALITY_SCAN_START",
    "_MOD_QUALITY_SCAN_END",
    "_MOD_QUALITY_SCAN_END_WIDE",
    "_MOD_MAX_UNIQUE_ID",
    "_MOD_MAX_SET_ID",
    "_MOD_HUFFMAN_CODE_START",
    "_HUFFMAN_REVERSE",
    "MOD_ITEM_NAMES",
    "_MAGIC_PREFIXES",
    "_MAGIC_SUFFIXES",
    "_CHARM_PREFIX_TABLE",
    "_SKILLTAB_PREFIX_NAMES",
    "_RARE_PREFIXES",
    "_RARE_SUFFIXES",
]


def main():
    lines = PARSER.read_text(encoding="utf-8").splitlines(keepends=True)
    total = len(lines)
    print(f"d2i_parser.py: {total} lines")

    # Build set of line indices (0-indexed) that belong to data sections
    data_line_indices: set[int] = set()
    for start, end in DATA_SECTIONS:
        for i in range(start - 1, end):  # convert to 0-indexed
            data_line_indices.add(i)

    print(f"Data lines to extract: {len(data_line_indices)}")

    # ── Write _d2i_tables.py ─────────────────────────────────────────────────
    tables_header = (
        '"""Static data tables for d2i_parser.py.\n\n'
        "Auto-extracted from d2i_parser.py by scripts/extract_d2i_tables.py.\n"
        "Do not edit this file's structure — add new data entries directly here.\n"
        '"""\n'
        "from __future__ import annotations\n\n"
    )

    data_body = []
    for i in range(total):
        if i in data_line_indices:
            data_body.append(lines[i])

    TABLES.write_text(tables_header + "".join(data_body), encoding="utf-8")
    tables_lines = tables_header.count("\n") + len(data_body)
    print(f"Wrote {TABLES} ({tables_lines} lines)")

    # ── Write updated d2i_parser.py ──────────────────────────────────────────
    # Build import block to insert
    import_block_lines = [
        IMPORT_LINE + "\n",
        *[f"    {name},\n" for name in IMPORT_NAMES],
        ")\n",
        "\n",
    ]

    # Rebuild d2i_parser.py:
    # 1. Keep all non-data lines
    # 2. Insert the import block after the existing imports section
    #    (right after the last top-level `import ...` line before any defs/classes)
    new_parser: list[str] = []
    import_block_inserted = False

    # Find where to insert the import — after line 30 ("log = logging.getLogger(...)")
    # which is the last setup line before data. We'll insert after the first blank line
    # that follows the last import statement.
    last_import_idx = 0
    for i in range(total):
        stripped = lines[i].strip()
        if stripped.startswith("import ") or stripped.startswith("from "):
            last_import_idx = i

    for i in range(total):
        if i in data_line_indices:
            continue  # skip extracted data

        if i == last_import_idx and not import_block_inserted:
            new_parser.append(lines[i])
            new_parser.extend(import_block_lines)
            import_block_inserted = True
            continue

        new_parser.append(lines[i])

    parser_lines = len(new_parser)
    print(f"Updated d2i_parser.py would have {parser_lines} lines (was {total})")

    # Show preview of what we'd change
    print("\n--- First 45 lines of new d2i_parser.py ---")
    for j, ln in enumerate(new_parser[:45], 1):
        print(f"{j:4}: {ln}", end="")

    print("\n\n--- Lines 130-145 of new d2i_parser.py (where data was) ---")
    for j, ln in enumerate(new_parser[129:145], 130):
        print(f"{j:4}: {ln}", end="")

    # Ask before writing
    print(f"\n\nReady to write:")
    print(f"  {TABLES}: {tables_lines} lines")
    print(f"  {PARSER}: {parser_lines} lines (down from {total})")
    answer = input("Proceed? [y/N] ").strip().lower()
    if answer != "y":
        print("Aborted.")
        return

    PARSER.write_text("".join(new_parser), encoding="utf-8")
    print(f"Done. Wrote {PARSER} ({parser_lines} lines)")


if __name__ == "__main__":
    main()
